name: "GitHub Issues"

targets:
  azure-arm-deploy:
    type: repo
    htmlUrl: https://github.com/Azure/arm-deploy
  azure-cli:
    type: repo
    htmlUrl: https://github.com/Azure/cli
  
output: "_reports"

reports:
  - name: GitHub Issues
    title: "{{{ config.name }}} Report"
    kind: markdown 
    timezoneOffset: +5.5
    sections: 
      - name: "repo-issues"
        targets: ['azure-arm-deploy']
        config: 
          breakdown-by-labels:
            [
              "default",
              "stale",
              "backlog"
            ]
      - name: "repo-issues"
        targets: ['azure-cli']
        config: 
          breakdown-by-labels:
            [
              "default",
              "stale",
              "backlog"
            ]
